### ISSUE TITLE
🐛 Bug : 영속성 컨텍스트가 실행상황과 디버그 상황에서 다르게 작동했던 부분

### ISSUE THREAD

**Issue by Qone2** [codestates-seb/seb40_main_001#95]
## Description

영속성 컨텍스트가 실행상황과 디버그 상황에서 다르게 작동했던 부분 버그 재현과 원인파악이 필요합니다.
리뷰 추가하는 부분에서 발생했던걸로 기억합니다.
작동하게끔 수정했지만 원인파악은 도움이 될걸로 생각합니다.

## 🗒 참고자료
> 보여지는 에러인 경우 스크린샷도 함께 첨부합니다.

## ETC
- 주의 사항 혹은 기타 내용

**Comment by hyeongiii** [comment]
리뷰를 추가하는 부분에서 publicEvaluation 계산할 때 실제 상황과 디버그 상황이 달랐고, 코드의 순서를 바꿈으로써 해결하였지만 다시 확인할 필요가 있음

**Comment by hyeongiii** [comment]
<img width="789" alt="image" src="https://user-images.githubusercontent.com/101054381/206634100-05c4beae-4755-4b2b-8517-36ef6dbc04db.png">
